name: Docker Datadog Aerospike Enterprise Agent Integration 

on:
  workflow_dispatch:
    inputs:
      docker_tag: 
         description: Docker Tag
         required: false
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Get latest release tag
      uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
      id: get-latest-tag

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

    - name: Docker login
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      env:
        DOCKER_MULTI_ARCH_PLATFORMS: linux/amd64,linux/arm64
      run: |
        VERSION_TAG=$(echo "${{ github.event.inputs.docker_tag }}" | xargs)

        if [ -n "$VERSION_TAG" ]; then

            echo "Using tag version $VERSION_TAG"
            docker buildx build --build-arg VERSION=$VERSION_TAG \
                  --platform $DOCKER_MULTI_ARCH_PLATFORMS \
                  --push . -f build/datadog.Dockerfile \
                  -t aerospike/datadog-aerospike-integration:latest \
                  -t aerospike/datadog-aerospike-integration:$VERSION_TAG
        fi 
